# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 511a5b1b0eda4f27f8e75786a4d7bc41bc8c81219aaa32d52e1e3e4616757d139dce9d4f67102c5c759138ade2cfa4c1e80ae57fbd003957c76f726448838e7a

test:
  secret_key_base: 4d4f4e74a39b34ac544012585ed1fc9207071735d6ec1b3e6c50329a5ab696f313b0395675191d945058f8868956655fe5e105f9e2d24a5daa8354f7b9b12a60

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
